worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Cấu hình xử lý Header và URL cực lớn cho SSO
    large_client_header_buffers 8 128k;
    client_header_buffer_size 64k;

    # Cấu hình bộ đệm Proxy toàn cục
    proxy_buffer_size          2048k;
    proxy_buffers              8 2048k;
    proxy_busy_buffers_size    2048k;

    # Redirect HTTP to HTTPS
    server {
        listen       80;
        server_name  factorymanagement.ttigroup.com.vn;
        return 301 https://$host$request_uri;
    }

    # HTTPS server
    server {
        listen       443 ssl;
        server_name  factorymanagement.ttigroup.com.vn;

        # Cấu hình bộ đệm Proxy tầng Server
        proxy_buffer_size          2048k;
        proxy_buffers              8 2048k;
        proxy_busy_buffers_size    2048k;

        # Cấu hình xử lý URL cực lớn (Đặt ở đây để ưu tiên cao nhất)
        large_client_header_buffers 8 128k;
        client_header_buffer_size 64k;
        ssl_buffer_size 128k;

        ssl_certificate      "c:/Users/idmcauto.svc/Desktop/Orgchart_TTI_onprem/ssl/fullchain.pem";
        ssl_certificate_key  "c:/Users/idmcauto.svc/Desktop/Orgchart_TTI_onprem/ssl/factoryapp.key";

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        location /uploads/ {
            alias "D:/Images emp/uploads/";
        }

        location / {
            proxy_pass http://127.0.0.1:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;

            # Cấu hình bộ đệm Proxy tầng Location (Ưu tiên cao nhất)
            proxy_buffer_size          2048k;
            proxy_buffers              8 2048k;
            proxy_busy_buffers_size    2048k;

            # Cấu hình xử lý dữ liệu lớn (Đã lược bỏ tham số lỗi)
            client_max_body_size       50M;
            
            # Timeout cực dài cho các xử lý nặng
            proxy_read_timeout 600;
            proxy_connect_timeout 600;
            proxy_send_timeout 600;
        }

        # Redirect server error pages to the static page /50x.html
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}
